plugins {
    id 'java'
    id 'java-library'
    id 'org.openapi.generator' version "7.11.0"
}

group = 'com.omar'
version = 'unspecified'

ext {
    jacksonAnnotationsVersion = '2.18.2'
    openApiJacksonBindVersion = '0.2.6'
    jakartaAnnotationVersion = '3.0.0'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation "com.fasterxml.jackson.core:jackson-annotations:${jacksonAnnotationsVersion}"
    implementation "com.fasterxml.jackson.core:jackson-databind:${jacksonAnnotationsVersion}"
    implementation "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:${jacksonAnnotationsVersion}"
    implementation "org.openapitools:jackson-databind-nullable:${openApiJacksonBindVersion}"
    implementation "jakarta.annotation:jakarta.annotation-api:${jakartaAnnotationVersion}"
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

openApiGenerate {
    generatorName = 'java'
    library = 'native'
    remoteInputSpec = 'https://date.nager.at/swagger/v3/swagger.json'
    outputDir = "${buildDir}/generated"
    apiPackage = 'com.omar.holidayclient.client'
    modelPackage = 'com.omar.holidayclient.model'
    configOptions = [
            skipOperationExample: "true",
            useJakartaEe: "true",
            dateLibrary: 'java8'
    ]
    importMappings = [
            "java.time.OffsetDateTime": "java.time.LocalDateTime"
    ]
    typeMappings = [
            OffsetDateTime: "LocalDateTime"
    ]
}

sourceSets {
    main {
        java {
            srcDirs += "${buildDir}/generated/src/main/java"
        }
    }
}

test {
    useJUnitPlatform()
}